#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check Prettier standards
yarn check-format ||
(
    echo '🚨 Prettier Check Failed. Make the required changes listed above, add changes and try to commit again.';
    false;
)

# Check ESLint Standards
yarn check-lint ||
(
        echo '🚨 EsLint Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)

# Check tsconfig standards
yarn check-types ||
(
    echo '🚨 Type Check Failed. Make the required changes listed above, add changes and try to commit again.'
    false;
)

# If everything passes... Now we can commit
echo 'Code looks good to me... Trying to build now.🤔'

yarn build ||
(
    echo '❌👷 Build failed 🔨❌ Next build failed: View the errors above to see why. '
    false;
)

# If everything passes... Now we can commit
echo 'I am committing this now. ✅'